name: Build Artifacts

on:
  push:
    branches: [ master ]
#  create: 
#    tags: releases/[1-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          python3 -m pip install clickable-ut
      - name: Build
        run: |
         CLICKABLE_FRAMEWORK=ubuntu-sdk-20.04 clickable build --verbose --arch ${{ matrix.arch }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: showdesktop_${{ matrix.arch }}
          path: build/*/app/*.click
          if-no-files-found: error
#          retention-days: 20
