name: Build Artifacts

on:
  push:
    branches: [ master ]
#  create: 
#    tags: releases/[1-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ubuntu-touch:
    strategy:
      fail-fast: false
      matrix:
        arch: [armhf, arm64, amd64]
        build: [Release, Debug]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#        with:
#          submodules: recursive
      - name: Install Dependencies
        run: |
          python3 -m pip install clickable-ut
        env:
          BUILD_TYPE: ${{ (matrix.build == 'Debug') && '--debug' || '' }}
          CLICKABLE_FRAMEWORK: ubuntu-sdk-20.04
      - name: Build
        run: |
         clickable build --verbose  ${BUILD_TYPE}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: "ubports-${{ matrix.arch }}--${{ matrix.build }}--click"
          path: "build/*/app/*.click"
          if-no-files-found: ignore
#          retention-days: 20
